# En este caso, haremos uso de una imagen que viene con PHP 7 y Apache
FROM php:5.6-apache
# Vamos a copiar el directorio src al default path que carga PHP al iniciar
#RUN echo "<?php echo "PHP5"; ?>" > /var/www/html/index.php
#COPY src/ /var/www/html/
