version: '3.8'
services:
  web:
    image: andr35/ej2compose-pet:v0.1.0
    ports:
      - "3000:3000"

  db:
    image: andr35/ej2compose-database:v0.1.0
    volumes:
      - pets-data:/var/lib/postgresql/data
 
volumes:
  pets-data: 

# Modificar la linea de ports por:
# ports:
#      - ":3000"
# Volver a ejecutar 
# docker-compose up 
# Escalar el servicio web a dos instancias de contenedores
# docker-compose scale web=2